import { declararTools } from "./tipos";

/** O CRM B2B é módulo opcional; o catálogo, o MCP externo e o runtime filtram por ele. */
export const TOOLS_B2B = declararTools([
  { name: "crm_list_companies", category: "read", rotulo: "Listar empresas", explicacao: "Busca empresas cadastradas na organização para consultar seus dados comerciais e vínculos.", oQueToca: "Empresas", risco: "seguro", pacotes: ["organizar"], modulo: "crm_b2b" },
  { name: "crm_get_company", category: "read", rotulo: "Ver empresa", explicacao: "Mostra os dados de uma empresa e as pessoas e contatos vinculados a ela.", oQueToca: "Empresa e vínculos", risco: "seguro", pacotes: ["organizar"], modulo: "crm_b2b" },
  { name: "crm_create_company", category: "write", rotulo: "Criar empresa", explicacao: "Cadastra uma empresa sem consultar automaticamente a BrasilAPI; dados externos exigem ação humana separada.", oQueToca: "Cadastro de empresa", risco: "atencao", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_update_company", category: "write", rotulo: "Atualizar empresa", explicacao: "Altera dados de uma empresa cadastrada sem chamar serviços externos automaticamente.", oQueToca: "Cadastro de empresa", risco: "atencao", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_list_people", category: "read", rotulo: "Listar pessoas B2B", explicacao: "Busca pessoas cadastradas na organização para consultar suas relações com empresas.", oQueToca: "Pessoas B2B", risco: "seguro", pacotes: ["organizar"], modulo: "crm_b2b" },
  { name: "crm_get_person", category: "read", rotulo: "Ver pessoa B2B", explicacao: "Mostra uma pessoa e os vínculos com empresas e contatos da mesma organização.", oQueToca: "Pessoa e vínculos", risco: "seguro", pacotes: ["organizar"], modulo: "crm_b2b" },
  { name: "crm_create_person", category: "write", rotulo: "Criar pessoa B2B", explicacao: "Cadastra uma pessoa na organização; o vínculo com empresa é uma ação explícita separada.", oQueToca: "Cadastro de pessoa", risco: "atencao", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_update_person", category: "write", rotulo: "Atualizar pessoa B2B", explicacao: "Altera nome, email ou notas de uma pessoa cadastrada na organização.", oQueToca: "Cadastro de pessoa", risco: "atencao", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_link_company_person", category: "write", rotulo: "Vincular pessoa e empresa", explicacao: "Associa uma pessoa a uma empresa da mesma organização, com cargo e função quando informados.", oQueToca: "Vínculo entre empresa e pessoa", risco: "atencao", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_update_company_person", category: "write", rotulo: "Atualizar vínculo B2B", explicacao: "Edita cargo, departamento e atributos de um vínculo entre empresa e pessoa existente.", oQueToca: "Vínculo entre empresa e pessoa", risco: "atencao", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_link_contact_person", category: "write", rotulo: "Associar contato a pessoa", explicacao: "Liga ou desliga um contato de uma pessoa B2B da mesma organização.", oQueToca: "Contato e pessoa B2B", risco: "atencao", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_list_import_batches", category: "read", rotulo: "Listar lotes de importação", explicacao: "Mostra os lotes B2B já enviados por uma pessoa e o estado de processamento de cada um.", oQueToca: "Histórico de importação", risco: "seguro", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
  { name: "crm_get_import_batch", category: "read", rotulo: "Ver lote de importação", explicacao: "Mostra as linhas e falhas de um lote B2B existente, sem enviar arquivo ou iniciar processamento.", oQueToca: "Lote de importação", risco: "seguro", pacotes: ["organizar"], modulo: "crm_b2b", apenasHumano: true },
]);
