import { declararTools } from "./tipos";

export const TOOLS_CAMPANHAS = declararTools([
  { name: "crm_list_campaigns", category: "read", rotulo: "Listar campanhas", explicacao: "Mostra as campanhas e seus estados na organização, sem iniciar ou alterar envios.", oQueToca: "Campanhas", risco: "seguro", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_get_campaign", category: "read", rotulo: "Ver campanha", explicacao: "Mostra detalhes e números de envio de uma campanha da organização atual.", oQueToca: "Campanha", risco: "seguro", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_preview_campaign", category: "read", rotulo: "Prever público da campanha", explicacao: "Calcula a prévia de elegíveis e exclusões antes de preparar a campanha.", oQueToca: "Público da campanha", risco: "seguro", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_get_campaign_metrics", category: "read", rotulo: "Ver métricas da campanha", explicacao: "Consulta os estados dos destinatários e as taxas da campanha, sem alterar envios.", oQueToca: "Métricas da campanha", risco: "seguro", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_prepare_campaign_launch", category: "read", rotulo: "Pedir confirmação para iniciar campanha", explicacao: "Abre a confirmação humana para iniciar envios; a ferramenta não envia mensagens.", oQueToca: "Início da campanha", risco: "seguro", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_create_campaign_draft", category: "write", rotulo: "Criar rascunho de campanha", explicacao: "Cria uma campanha em rascunho com público, canal e base legal, sem enviar mensagens.", oQueToca: "Rascunho de campanha", risco: "atencao", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_update_campaign_draft", category: "write", rotulo: "Editar rascunho de campanha", explicacao: "Altera apenas uma campanha em rascunho e atualiza a versão do conteúdo quando necessário.", oQueToca: "Rascunho de campanha", risco: "atencao", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_update_campaign_pacing", category: "write", rotulo: "Ajustar ritmo da campanha", explicacao: "Muda o ritmo ou números de uma campanha ativa sem tocar na mensagem já preparada.", oQueToca: "Ritmo da campanha", risco: "atencao", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_prepare_campaign", category: "write", rotulo: "Preparar campanha", explicacao: "Congela o público da campanha pela transição oficial, sem iniciar o envio.", oQueToca: "Público da campanha", risco: "atencao", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_pause_campaign", category: "write", rotulo: "Pausar campanha", explicacao: "Interrompe novos envios de uma campanha pela transição oficial de pausa.", oQueToca: "Envios da campanha", risco: "atencao", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_cancel_campaign", category: "write", rotulo: "Cancelar campanha", explicacao: "Cancela definitivamente novos envios e mantém o histórico dos destinatários.", oQueToca: "Envios da campanha", risco: "critico", pacotes: ["campanhas"], apenasHumano: true },
  { name: "crm_duplicate_campaign", category: "write", rotulo: "Duplicar campanha", explicacao: "Cria um novo rascunho sem copiar destinatários, resultados ou agenda de envio.", oQueToca: "Campanha", risco: "atencao", pacotes: ["campanhas"], apenasHumano: true },
]);
