import { declararTools } from "./tipos";

export const TOOLS_CRM_COMPLETO = declararTools([
  { name: "crm_create_contact", category: "write", rotulo: "Criar contato", explicacao: "Cadastra uma pessoa com os dados e consentimentos informados, preservando as regras de duplicidade.", oQueToca: "Contatos", risco: "atencao", pacotes: ["atender", "vender"] },
  { name: "crm_update_contact", category: "write", rotulo: "Atualizar contato", explicacao: "Atualiza os dados cadastrais, consentimentos e informações próprias de uma pessoa existente.", oQueToca: "Contatos", risco: "atencao", pacotes: ["atender", "vender"] },
  { name: "crm_get_contact_timeline", category: "read", rotulo: "Ver histórico do contato", explicacao: "Mostra em ordem o que aconteceu com a pessoa e com as oportunidades vinculadas a ela.", oQueToca: "Histórico do contato", risco: "seguro", pacotes: ["atender", "vender"] },
  { name: "crm_delete_contact", category: "write", rotulo: "Anonimizar contato", explicacao: "Remove os dados pessoais de forma irreversível e preserva o histórico exigido pela operação.", oQueToca: "Contatos", risco: "critico", pacotes: ["organizar"], apenasHumano: true },
  { name: "crm_get_lead_timeline", category: "read", rotulo: "Ver histórico da oportunidade", explicacao: "Mostra movimentações, edições, tarefas e desfechos de uma oportunidade sem misturar outras.", oQueToca: "Histórico da oportunidade", risco: "seguro", pacotes: ["vender"] },
  { name: "crm_move_lead_pipeline", category: "write", rotulo: "Levar oportunidade a outro funil", explicacao: "Cria a continuidade no funil destino e encerra a origem sem perder eventos nem histórico.", oQueToca: "Oportunidade e funis", risco: "atencao", pacotes: ["vender"] },
  { name: "crm_get_pipeline", category: "read", rotulo: "Ver um funil completo", explicacao: "Mostra a configuração de um funil, suas colunas, campos próprios e motivos de perda.", oQueToca: "Funil de vendas", risco: "seguro", pacotes: ["vender", "organizar"] },
  { name: "crm_create_pipeline", category: "write", rotulo: "Criar funil", explicacao: "Cria um novo funil já pronto para receber e encerrar oportunidades sem deixar um quadro vazio.", oQueToca: "Funil de vendas", risco: "atencao", pacotes: ["organizar"], apenasHumano: true },
  { name: "crm_update_pipeline", category: "write", rotulo: "Atualizar funil", explicacao: "Altera nome, descrição, ordem e papel padrão de um funil existente de forma controlada.", oQueToca: "Funil de vendas", risco: "atencao", pacotes: ["organizar"], apenasHumano: true },
  { name: "crm_archive_pipeline", category: "write", rotulo: "Arquivar funil", explicacao: "Tira um funil de uso sem apagar seu histórico e recusa quando alguma entrada ainda depende dele.", oQueToca: "Funil de vendas", risco: "critico", pacotes: ["organizar"], apenasHumano: true },
  { name: "crm_update_pipeline_schema", category: "write", rotulo: "Configurar campos do funil", explicacao: "Define os campos próprios, nomes usados pela empresa e motivos de perda aceitos no funil.", oQueToca: "Configuração do funil", risco: "critico", pacotes: ["organizar"], apenasHumano: true },
  { name: "crm_set_custom_field_values", category: "write", rotulo: "Preencher campos próprios", explicacao: "Preenche ou limpa informações configuradas pela empresa em um contato ou oportunidade.", oQueToca: "Contatos e oportunidades", risco: "atencao", pacotes: ["atender", "vender"] },
  { name: "crm_list_tasks", category: "read", rotulo: "Listar tarefas", explicacao: "Mostra tarefas comerciais por prazo, situação, prioridade, responsável, contato ou oportunidade.", oQueToca: "Tarefas comerciais", risco: "seguro", pacotes: ["vender", "organizar"] },
  { name: "crm_get_task", category: "read", rotulo: "Ver tarefa", explicacao: "Abre os detalhes de uma tarefa comercial sem confundi-la com um compromisso da agenda.", oQueToca: "Tarefas comerciais", risco: "seguro", pacotes: ["vender", "organizar"] },
  { name: "crm_create_task", category: "write", rotulo: "Criar tarefa", explicacao: "Cria um próximo passo interno e o registra no histórico quando ligado a uma oportunidade.", oQueToca: "Tarefas comerciais", risco: "atencao", pacotes: ["vender", "organizar"] },
  { name: "crm_update_task", category: "write", rotulo: "Atualizar tarefa", explicacao: "Edita, conclui, reabre ou cancela uma tarefa e registra a conclusão no histórico do negócio.", oQueToca: "Tarefas comerciais", risco: "atencao", pacotes: ["vender", "organizar"] },
  { name: "crm_delete_task", category: "write", rotulo: "Excluir tarefa", explicacao: "Apaga definitivamente uma tarefa; cancelar preserva mais histórico e deve ser preferido quando couber.", oQueToca: "Tarefas comerciais", risco: "critico", pacotes: ["organizar"], apenasHumano: true },
  { name: "crm_list_tag_vocabulary", category: "read", rotulo: "Ver marcadores e usos", explicacao: "Mostra marcadores, cores e quantas vezes aparecem em cada parte do atendimento e das vendas.", oQueToca: "Marcadores", risco: "seguro", pacotes: ["atender", "vender", "organizar"] },
  { name: "crm_update_tag", category: "write", rotulo: "Editar marcador", explicacao: "Renomeia um marcador em todos os lugares ou muda a cor usada para identificá-lo.", oQueToca: "Marcadores", risco: "atencao", pacotes: ["organizar"], apenasHumano: true },
  { name: "crm_merge_or_delete_tag", category: "write", rotulo: "Juntar ou excluir marcador", explicacao: "Junta dois marcadores ou remove um deles de todos os registros em uma única operação controlada.", oQueToca: "Marcadores", risco: "critico", pacotes: ["organizar"], apenasHumano: true },
]);
