import { declararTools } from "./tipos";

export const TOOLS_MANAGED_CLIENTS = declararTools([
  {
    name: "crm_list_managed_client_presets",
    category: "read",
    rotulo: "Ver perfis de clientes gerenciados",
    explicacao: "Mostra os tipos de negócio preparados, suas áreas e se a criação de uma nova organização já está liberada.",
    oQueToca: "Planejamento de novos clientes",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
  {
    name: "crm_preflight_managed_client",
    category: "read",
    rotulo: "Conferir plano de cliente gerenciado",
    explicacao: "Mostra a organização proposta, o convidado, a divisão de áreas e os bloqueios de segurança antes de qualquer criação.",
    oQueToca: "Planejamento de novos clientes",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
  {
    name: "crm_create_managed_client",
    category: "write",
    rotulo: "Criar cliente gerenciado",
    explicacao: "Conferir o plano e, só após confirmação explícita de um administrador da plataforma, criar a organização gerenciada e convidar o primeiro usuário.",
    oQueToca: "Nova organização, perfil gerenciado, vínculo do gestor e convite",
    risco: "critico",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
  {
    name: "crm_configure_managed_internet_provider",
    category: "write",
    rotulo: "Preparar operação de provedor gerenciado",
    explicacao: "Confere o plano e, após confirmação, cria o funil, os motivos, campos e marcadores de um provedor de internet gerenciado.",
    oQueToca: "Funil, etapas, motivos de perda, campos e marcadores do cliente",
    risco: "critico",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
  {
    name: "crm_configure_managed_internet_provider_ai",
    category: "write",
    rotulo: "Preparar IA e atendimento humano do provedor",
    explicacao: "Mostra pendências ou prepara agentes, roteador e lembretes internos em rascunho, sem publicar nem enviar mensagens.",
    oQueToca: "Agentes, roteador de intenções e rascunhos de acompanhamento do provedor",
    risco: "critico",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
]);
