import { declararTools } from "./tipos";

export const TOOLS_PARITY_162 = declararTools([
  {
    name: "crm_get_tags_report",
    category: "read",
    rotulo: "Consultar relatório por etiqueta",
    explicacao:
      "Consulta volume, desfecho e espera dos atendimentos por etiqueta, com período, fuso e indicação de dados parciais.",
    oQueToca: "Relatório das conversas",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
  {
    name: "crm_create_honorarios_contrato",
    category: "write",
    rotulo: "Registrar contrato de honorários",
    explicacao:
      "Registra o modelo e os valores combinados no CRM, sem gerar cobrança ou movimentar dinheiro.",
    oQueToca: "Contrato de honorários",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    modulo: "honorarios",
  },
  {
    name: "crm_create_honorarios_parcela",
    category: "write",
    rotulo: "Registrar parcela de honorários",
    explicacao:
      "Acrescenta uma parcela pendente ao calendário de um contrato interno, sem emitir cobrança ou registrar pagamento.",
    oQueToca: "Parcelas de honorários",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    modulo: "honorarios",
  },
  {
    name: "crm_list_honorarios_contratos",
    category: "read",
    rotulo: "Listar contratos de honorários",
    explicacao:
      "Consulta contratos internos da organização, com filtro opcional por negócio e sem efeitos financeiros externos.",
    oQueToca: "Honorários",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
    modulo: "honorarios",
  },
  {
    name: "crm_list_proposals",
    category: "read",
    rotulo: "Listar propostas comerciais",
    explicacao:
      "Consulta as propostas da organização por situação e negócio, para acompanhar os registros comerciais internos.",
    oQueToca: "Propostas comerciais",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_get_proposal",
    category: "read",
    rotulo: "Consultar proposta e itens",
    explicacao:
      "Mostra a proposta com seus itens e os preços atuais do catálogo para conferir alterações antes da revisão humana.",
    oQueToca: "Propostas comerciais",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_update_draft_proposal",
    category: "write",
    rotulo: "Editar rascunho de proposta",
    explicacao:
      "Atualiza um rascunho na revisão informada e recalcula seus itens e total, preservando a moeda e o envio humano.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_get_proposal_document",
    category: "read",
    rotulo: "Consultar documento estruturado",
    explicacao:
      "Consultar documento estruturado dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_update_proposal_document_field",
    category: "write",
    rotulo: "Preencher campo do documento",
    explicacao:
      "Preencher campo do documento dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_update_proposal_document_section",
    category: "write",
    rotulo: "Editar seção do documento",
    explicacao:
      "Editar seção do documento dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_create_proposal_revision",
    category: "write",
    rotulo: "Criar revisão em rascunho",
    explicacao:
      "Criar revisão em rascunho dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_discard_draft_proposal",
    category: "write",
    rotulo: "Descartar rascunho de proposta",
    explicacao:
      "Descartar rascunho de proposta dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_list_proposal_templates",
    category: "read",
    rotulo: "Listar modelos da organização",
    explicacao:
      "Listar modelos da organização dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_get_proposal_template",
    category: "read",
    rotulo: "Consultar estrutura do modelo",
    explicacao:
      "Consultar estrutura do modelo dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_create_proposal_template",
    category: "write",
    rotulo: "Criar modelo comercial",
    explicacao:
      "Criar modelo comercial dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_customize_proposal_template",
    category: "write",
    rotulo: "Personalizar base comercial",
    explicacao:
      "Personalizar base comercial dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_set_proposal_template_visibility",
    category: "write",
    rotulo: "Mostrar ou ocultar modelo",
    explicacao:
      "Mostrar ou ocultar modelo dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_update_proposal_template",
    category: "write",
    rotulo: "Editar modelo comercial",
    explicacao:
      "Editar modelo comercial dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_deactivate_proposal_template",
    category: "write",
    rotulo: "Desativar cópia de modelo",
    explicacao:
      "Desativar cópia de modelo dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_get_proposal_settings",
    category: "read",
    rotulo: "Consultar configuração de propostas",
    explicacao:
      "Consultar configuração de propostas dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_update_proposal_defaults",
    category: "write",
    rotulo: "Editar padrões comerciais",
    explicacao:
      "Editar padrões comerciais dentro da organização, preservando os controles humanos de envio, decisão e aplicação de sugestões.",
    oQueToca: "Propostas comerciais",
    risco: "atencao",
    pacotes: ["organizar"],
    apenasHumano: true,
    capacidade: "propostas",
  },
  {
    name: "crm_list_channel_groups",
    category: "read",
    rotulo: "Consultar grupos do número",
    explicacao:
      "Lê grupos presentes e grupos ligados que saíram do número, sem alterar o recebimento ou enviar mensagens.",
    oQueToca: "Grupos do canal",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
  {
    name: "crm_search_organization_knowledge",
    category: "read",
    rotulo: "Consultar acervo da organização",
    explicacao:
      "Busca trechos do material publicado com o limiar canônico, usando embedding e respeitando o teto de consultas.",
    oQueToca: "Acervo da organização",
    risco: "seguro",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
]);
